"""Closed official-client source admission for forty existing A12 corpse pointers."""

from __future__ import annotations

import hashlib
import json
import sys
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path[:0] = [
    str(ROOT / "tools/content-census"),
    str(ROOT / "tools/content-migration"),
    str(ROOT / "tools/content-schema/item-authoring"),
]
import appearance_membership
import engine_items
from item_id_alias_table import tibia_key
from item_official_navigation import admission_ids

PROFILE = "OTERYN_OFFICIAL_CLIENT_WORLD_APPEARANCE/v1"
QUALIFICATION = Path(__file__).parent / "samples/qualified-official-corpses-15.30.json"
QUALIFICATION_SHA256 = (
    "11260bf4bf7292c883d248a19b42bb6eaeaae4e9b4e7765435fbd89bf5476e51"
)
CENSUS = Path(__file__).parent / "samples/census-official-corpses-15.30.json"
IDS = frozenset(
    {
        21887,
        35384,
        35388,
        35600,
        35846,
        43666,
        43762,
        43771,
        43959,
        44447,
        44664,
        44665,
        44666,
        44667,
        44668,
        44669,
        44670,
        44671,
        44684,
        44685,
        44686,
        44687,
        44709,
        44713,
        44717,
        48108,
        48112,
        48271,
        48349,
        48353,
        48366,
        48382,
        48403,
        48404,
        48405,
        48406,
        48414,
        48416,
        49124,
        51560,
    }
)
KEYS = frozenset(tibia_key(item_id) for item_id in IDS)


def digest(value):
    return hashlib.sha256(
        json.dumps(
            value, sort_keys=True, separators=(",", ":"), ensure_ascii=False
        ).encode()
    ).hexdigest()


def qualification():
    raw = QUALIFICATION.read_bytes()
    if hashlib.sha256(raw).hexdigest() != QUALIFICATION_SHA256:
        raise ValueError("OFFICIAL_CORPSE_QUALIFICATION_DIGEST")
    document = json.loads(raw)
    rows = document["records"]
    if len(rows) != 40 or {row["appearance_id"] for row in rows} != IDS:
        raise ValueError("OFFICIAL_CORPSE_CLOSED_SCOPE")
    return document


@lru_cache(maxsize=1)
def source_inputs():
    """One immutable source snapshot per validator/generator process."""
    document = qualification()
    source = document["source"]
    index, manifests = appearance_membership.load_admitted()
    spec = index["files"][-1]
    manifest = manifests[index["newest"]]
    if (
        index["newest"] != "client-15.30"
        or spec["label"] != index["newest"]
        or source["engine"] != "official_client"
        or source["profile"] != PROFILE
        or source["client_version"] != "15.30"
        or source["revision"] != spec["appearances_sha256"]
        or source["membership_manifest_sha256"] != spec["manifest_sha256"]
        or source["membership_entries_sha256"] != manifest["entries_sha256"]
    ):
        raise ValueError("OFFICIAL_CORPSE_CURRENT_MEMBERSHIP")
    raw = (ROOT / source["artifact"]).read_bytes()
    if (
        hashlib.sha256(raw).hexdigest() != source["revision"]
        or appearance_membership.manifest_entries(raw) != manifest["entries"]
    ):
        raise ValueError("OFFICIAL_CORPSE_SOURCE_ARTIFACT")
    members = {row[0]: row for row in manifest["entries"]}
    admission = document["admission_source"]
    admitted = admission_ids((ROOT / admission["path"]).read_text(), admission)
    definitions = {}
    for path in (ROOT / "content/items/definitions").glob("items-*.json"):
        for row in json.loads(path.read_bytes())["records"]:
            definition = row["definition"]
            definitions[definition["identity"]["key"]] = definition
    taxonomy = {
        row["target"]["key"]
        for row in json.loads(
            (ROOT / "content/items/taxonomy/items.json").read_bytes()
        )["records"]
    }
    bound = {
        row["target"]["key"]
        for row in json.loads(
            (ROOT / "imports/crystalserver/bindings/items.json").read_bytes()
        )["bindings"]
    }
    reviewed = {row["appearance_id"]: row for row in document["records"]}
    owners = set()
    for directory in ("objects", "terrain"):
        for path in (ROOT / "content/world" / directory).glob("*.json"):
            for record in json.loads(path.read_bytes()).get("records", []):
                entry = reviewed.get(record["provenance"]["source_item_id"])
                # A previously generated byte-exact qualified record is itself, not a competing owner.
                if entry and digest(record) == entry["validated_record_sha256"]:
                    continue
                owners.add(record["provenance"]["item_pointer"]["key"])
    return (
        document,
        members,
        engine_items.load_appearance_objects(raw),
        definitions,
        admitted,
        taxonomy,
        owners,
        bound,
    )


def build_record(
    entry, appearance, definition, member, admitted, taxonomy, owners, bound, source
):
    import world_objects

    item_id = entry["appearance_id"]
    key = tibia_key(member[0]) if member else None
    if (
        item_id not in IDS
        or item_id not in admitted
        or not member
        or member[0] != item_id
        or member[1:]
        != [entry["identity_projection_sha256"], entry["current_record_sha256"]]
        or appearance.get("id") != item_id
        or digest(appearance) != entry["decoded_record_sha256"]
        or not definition
        or definition.get("identity") != entry["target"]
        or entry["target"]
        != {"family": "Item", "key": key, "revision": "definition-r1"}
        or definition.get("materializable") is not False
        or definition.get("stack_class") != "Unknown"
        or key in taxonomy
        or key in owners
        or key in bound
    ):
        raise ValueError("OFFICIAL_CORPSE_IDENTITY_OR_PRECEDENCE")
    presentation = definition.get("semantics", {}).get("presentation", {})
    name = presentation.get("value", {}).get("name", {})
    if (
        presentation.get("state") in ("CONFLICT", "NOT_APPLICABLE")
        or name.get("state") in ("CONFLICT", "NOT_APPLICABLE")
        or name.get("state") == "KNOWN"
        and name["value"] != appearance.get("name")
    ):
        raise ValueError("OFFICIAL_CORPSE_PRESENTATION")
    flags = appearance.get("flags", {})
    if not any(
        flags.get(field) is True for field in engine_items.CORPSE_FLAGS
    ) or engine_items.non_item_route(None, {}, flags, item_id) != (
        "WorldObject",
        "corpse",
    ):
        raise ValueError("OFFICIAL_CORPSE_POSITIVE_ROUTE")
    record = world_objects.build_record(
        "WorldObject", item_id, key, "corpse", None, appearance, source
    )
    if digest(record) != entry["validated_record_sha256"]:
        raise ValueError("OFFICIAL_CORPSE_REVIEWED_RECORD")
    return record


def expected_record(item_id, inputs=None):
    document, members, client, definitions, admitted, taxonomy, owners, bound = (
        inputs or source_inputs()
    )
    entry = next(
        (row for row in document["records"] if row["appearance_id"] == item_id), None
    )
    if entry is None:
        raise ValueError("OFFICIAL_CORPSE_UNREVIEWED_ID")
    return build_record(
        entry,
        client.get(item_id, {}),
        definitions.get(entry["target"]["key"]),
        members.get(item_id),
        admitted,
        taxonomy,
        owners,
        bound,
        document["source"],
    )


def validate_record(record):
    try:
        expected = expected_record(record["provenance"]["source_item_id"])
        if record != expected:
            return ["OFFICIAL_CORPSE_SOURCE_OR_RECORD_CHANGED"]
    except (KeyError, ValueError) as error:
        return [str(error)]
    return []


def outputs(existing_keys, start):
    import world_objects

    inputs = source_inputs()
    records = [expected_record(item_id, inputs) for item_id in sorted(IDS)]
    if existing_keys & KEYS:
        raise ValueError("OFFICIAL_CORPSE_EXISTING_WORLD_OWNER")
    for record in records:
        errors = world_objects.validate_record(record)
        if errors:
            raise ValueError(f"OFFICIAL_CORPSE_INVALID_RECORD:{errors[:3]}")
    files = {
        f"content/world/objects/objects-{start:05d}-{start + 39:05d}.json": world_objects.canonical_bytes(
            {"family": "WorldObject", "records": records}
        )
        + b"\n"
    }
    census = {
        "schema": "OTERYN_OFFICIAL_WORLD_CORPSE_CENSUS/v1",
        "source": inputs[0]["source"],
        "qualification_sha256": QUALIFICATION_SHA256,
        "records": {
            "total": 40,
            "by_family": {"WorldObject": 40},
            "digest_sha256": hashlib.sha256(
                b"".join(world_objects.canonical_bytes(row) + b"\n" for row in records)
            ).hexdigest(),
        },
    }
    files[CENSUS.relative_to(ROOT).as_posix()] = (
        world_objects.canonical_bytes(census) + b"\n"
    )
    return files
