"""Register schema-preserving spell collections without changing legacy identities."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path

import import_spell_families as spell_import
import import_current_spell_sources as current_sources

ROOT = Path(__file__).resolve().parents[2]
FAMILY_INDEXES = {
    "Ability": "content/abilities/definitions/index.json",
    "Effect": "content/abilities/effects/index.json",
    "Formula": "content/abilities/formulas/index.json",
    "Creature": "content/creatures/definitions/index.json",
    "Presentation": "content/presentations/definitions/index.json",
    "Item": "content/items/index.json",
}
# Production V7 pins (D879, D887): repository-owned files pinned by digest after the
# overlay stages, whose base digests cover the manifest without them.
REPOSITORY_PINS = {
    "item_keys": "tools/content-schema/native-gameplay/item-keys.json",
    "progression": "rulesets/character/experience/native-section.json",
    "loot_tables": "tools/content-schema/native-gameplay/loot-tables.json",
}
NATIVE_MANIFEST = "content/spells.manifest.json"
# The closed coin table of apps/game-server/src/domain/currency.rs (D175/D176): the
# Item provider gains exactly these profiles, generated by build_source_item_profiles.py.
COIN_PROFILES = "tools/content-schema/native-gameplay/coin-item-profiles.json"
COIN_KEYS = {f"oteryn:item.tibia.i{i}" for i in (3031, 3035, 3043)}
COIN_ADMISSION = {
    "materializable": True,
    "stack_class": "StackCapable",
    "legal_destinations": ["CharacterInventory", "Ground"],
}


def pin_repository_inputs(root: Path, generated: dict[str, bytes]) -> None:
    manifest = json.loads(generated[NATIVE_MANIFEST])
    for key, path in REPOSITORY_PINS.items():
        manifest[key] = {
            "path": Path(os.path.relpath(path, "content")).as_posix(),
            "sha256": hashlib.sha256((root / path).read_bytes()).hexdigest(),
        }
    generated[NATIVE_MANIFEST] = spell_import.canonical_bytes(manifest)


def admit_coin_profiles(root: Path, generated: dict[str, bytes]) -> None:
    path = spell_import.PROVIDER_DESTINATIONS["item_profiles"]
    document = json.loads(generated[path])
    coins = json.loads((root / COIN_PROFILES).read_bytes())
    present = {r["production_definition"]["production_key"] for r in document["records"]}
    keys = [r["production_definition"]["production_key"] for r in coins["records"]]
    stack = {"state": "KNOWN", "value": {
        "stackable": {"state": "KNOWN", "value": True},
        "stack_max": {"state": "KNOWN", "value": 100},
    }}
    if (
        coins["schema"] != "OTERYN_NATIVE_COIN_ITEM_PROFILES/v1"
        or len(keys) != len(COIN_KEYS) or set(keys) != COIN_KEYS or present & COIN_KEYS
        or any(r["admission"] != COIN_ADMISSION or r["semantics"]["stack"] != stack
               for r in coins["records"])
    ):
        raise ValueError("COIN_ITEM_PROFILES_DISAGREE_WITH_D176")
    document["records"] = sorted(
        document["records"] + coins["records"],
        key=lambda r: int(r["production_definition"]["production_key"].rsplit(".i", 1)[1]),
    )
    data = (json.dumps(document, indent=2, ensure_ascii=False) + "\n").encode()
    if hashlib.sha256(data).hexdigest() != coins["item_profiles_sha256"]:
        raise ValueError("COIN_ITEM_PROFILES_PROVIDER_DRIFT")
    generated[path] = data
    manifest = json.loads(generated[NATIVE_MANIFEST])
    manifest["item_profiles"]["sha256"] = hashlib.sha256(data).hexdigest()
    generated[NATIVE_MANIFEST] = spell_import.canonical_bytes(manifest)


def encoded(value: object, *, registry: bool = False) -> bytes:
    options = {"indent": 2} if registry else {"separators": (",", ":")}
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, **options) + "\n").encode()


def outputs(root: Path = ROOT) -> dict[str, bytes]:
    """Prepare the entire registration before writing any file.

    Legacy shard counts describe legacy definitions only. Imported collections have
    their own schema, identity and counts; they are not silently coerced into v2.
    """
    baseline = spell_import.baseline_outputs(root)
    generated = baseline
    generated = current_sources.outputs(root, generated)
    from compose_monster_current_sources import compose
    generated = compose(root, baseline, generated)
    admit_coin_profiles(root, generated)
    pin_repository_inputs(root, generated)
    descriptors = spell_import.descriptors(root, generated)
    for family, path in FAMILY_INDEXES.items():
        index = json.loads((root / path).read_bytes())
        index["spell_imports"] = descriptors.get(family, [])
        # Registration is semantic metadata; retain the existing index's explicit
        # pretty/compact convention instead of reformatting unchanged family data.
        generated[path] = encoded(index, registry=b'\n  "' in (root / path).read_bytes())
    for path, prefix in (
        ("content/presentations/bindings/index.json", "content/presentations/bindings/"),
        ("rulesets/progression/wheel-of-destiny/index.json", "rulesets/progression/wheel-of-destiny/"),
    ):
        index = json.loads((root / path).read_bytes())
        index["spell_imports"] = [
            entry for entries in descriptors.values() for entry in entries
            if entry["path"].startswith(prefix)
        ]
        generated[path] = encoded(index, registry=b'\n  "' in (root / path).read_bytes())
    registration = {
        "native_manifest": "content/spells.manifest.json",
        "collections": descriptors,
        "legacy_family_counts_unchanged": True,
        "runtime_activation": False,
    }
    manifest = json.loads((root / "content/manifest.json").read_bytes())
    managed = {row["path"] for row in manifest["managed_files"]} | set(generated)
    manifest["managed_files"] = [{"path": path} for path in sorted(managed)]
    manifest["spell_import"] = registration
    generated["content/manifest.json"] = encoded(manifest, registry=True)
    lock = json.loads((root / "content/content.lock.json").read_bytes())
    lock["spell_import"] = registration
    generated["content/content.lock.json"] = encoded(lock, registry=True)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = outputs()
    if args.check:
        drift = [path for path, data in generated.items()
                 if not (ROOT / path).is_file() or (ROOT / path).read_bytes() != data]
        if drift:
            raise SystemExit("Spell import drift: " + ", ".join(drift))
    else:
        for path, data in generated.items():
            destination = ROOT / path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
    print(f"PASS registered spell import files={len(generated)} activation=false")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
