from pathlib import Path
import json,hashlib,re,collections
from fractions import Fraction
base=Path('/tmp/monster-wiki-priority-20261004');lane=base/'mitigation_b';inputfile=base/'mitigation_b.json';inp=json.loads(inputfile.read_text());repo=Path('/workspace/monster-main-reconciliation-20261004');pop=Path('/tmp/monster-mechanics-execution-20261004/population');nativepath=repo/'content/creatures/definitions/spell-native-profiles.json';native=json.loads(nativepath.read_text());nativeby={r['profile']['target']['key']:r for r in native['records']};wiki_path=Path('/workspace/monster-completion/tools/content-schema/monster-authoring/samples/wiki-population-2026-09-27.json');wiki=json.loads(wiki_path.read_text());wikiby={r['monster']:r for r in wiki['monsters']};proposals=[];blocked=[]
def sha(b):return hashlib.sha256(b).hexdigest()
def ratio(x):return Fraction(x['numerator'],x['denominator'])
for row in inp['rows']:
 ref=row['target'];slug=ref['key'].split('oteryn:creature.',1)[-1];mfile=pop/'bundles'/slug/'manifest.json';bfile=mfile.with_name('monster.json');manifest=json.loads(mfile.read_text());bundle=json.loads(bfile.read_text());value=bundle['creature']['stats'].get('mitigation_percent');assert value and ratio(value)==ratio(row['canonical']),(slug,value,row['canonical'])
 actual=nativeby[ref['key']]['profile']['data']['profile'];assert ('mitigation'in actual)==row['old_present'] and actual.get('mitigation')==row['old'],slug
 active=[e for e in manifest['entries']if'mitigation'in e.get('destination','').lower()and e.get('status')=='mapped'];superseded=[e for e in manifest['entries']if'mitigation'in e.get('destination','').lower()and e.get('status')!='mapped'];est=[e for e in active if'OWNER_ACCEPTED_NON_GLOBAL_ESTIMATE'in e.get('resolution','')];wes=[e for e in active if manifest['sources'][e['source_index']].get('kind')=='mediawiki'];cached=wikiby.get(slug);numericwiki=[]
 if cached:
  for fact in cached.get('rows',[]):
   if fact.get('field')=='mitigation_percent'and fact.get('status')in ['MATCH','DIFF']and isinstance(fact.get('wiki'),(int,float)):
    raw=str(fact.get('wiki_raw',fact['wiki'])).strip()
    if re.fullmatch(r'\d+(?:\.\d+)?',raw)and Fraction(raw)==ratio(value):numericwiki.append(fact)
 if wes:
  # Current mapped per-field Wiki promotion receipt is decisive. Historical estimates are never consulted ahead of this.
  tag='WIKI_CONFIRMED';chosen=wes;reason='CURRENT_MAPPED_WIKI_FIELD_RECEIPT_VALUE_EQUALS_CURRENT_CANONICAL; cached access only'
  if cached and cached.get('wiki_title')not in [e.get('source_file')for e in wes]:reason+='; retained current promotion source differs from older cached snapshot title'
 elif est:tag='ACCEPTED_PROJECT_ESTIMATE';chosen=est;reason='CURRENT_OWNER_ACCEPTED_NON_GLOBAL_ESTIMATE; no current mapped Wiki mitigation receipt; existing accepted fallback preserved without recomputation'
 elif active:tag='SOURCE_ONLY';chosen=active;reason='CURRENT_DONOR_SOURCE_FIELD_ONLY; global Wiki mitigation unconfirmed; existing canonical adopted source value preserved'
 else:tag='UNKNOWN';chosen=[];reason='NO_CURRENT_MAPPED_FIELD_SOURCE';blocked.append(slug)
 evidence=[{'manifest_entry':e,'source':manifest['sources'][e['source_index']]}for e in chosen]
 canonical_path=repo/row['canonical_path'];c=json.loads(canonical_path.read_text());record=next(r for r in c['records']if r['definition']['identity']['key']==ref['key']);cvalue=record['authoring']['profile']['mitigation'];assert ratio(cvalue)==ratio(row['canonical'])
 proposals.append({'target':ref,'field':'mitigation','old_present':row['old_present'],'old':row['old'],'new_present':row['canonical_present'],'new':row['canonical'],'provenance':tag,'wiki_confirmed':tag=='WIKI_CONFIRMED','global_parity': 'WIKI_FIELD_VALUE_CONFIRMED_ONLY'if tag=='WIKI_CONFIRMED'else'NOT_CONFIRMED','reason':reason,'canonical_path':row['canonical_path'],'canonical_file_sha256':sha(canonical_path.read_bytes()),'source_bindings':row['source_bindings'],'evidence':{'current_field_manifest':str(mfile),'manifest_sha256':sha(mfile.read_bytes()),'current_bundle':str(bfile),'bundle_sha256':sha(bfile.read_bytes()),'current_bundle_value':value,'active_field_sources':evidence,'superseded_mitigation_entries':superseded,'cached_wiki_snapshot':str(wiki_path)if numericwiki else None,'cached_wiki_snapshot_sha256':sha(wiki_path.read_bytes())if numericwiki else None,'cached_wiki_numeric_rows':numericwiki,'cached_wiki_identity_binding':{'monster':cached.get('monster'),'wiki_title':cached.get('wiki_title'),'page_id':cached.get('page_id'),'revision_id':cached.get('cut_revision_id')}if numericwiki else None,'source_access_mode':'cached local bundle field provenance and cached Wiki dataset; no new internet read'}})
result={'status':'GUARDED_BATCH_PROPOSAL_COMPLETE_NO_PRODUCT_WRITES','input':str(inputfile),'input_sha256':sha(inputfile.read_bytes()),'native_path':str(nativepath),'native_sha256':sha(nativepath.read_bytes()),'expected_input_native_sha256':inp['native_sha256'],'native_generation_matches_input':sha(nativepath.read_bytes())==inp['native_sha256'],'row_count':len(proposals),'counts':dict(collections.Counter(r['provenance']for r in proposals)),'all_new_values_equal_current_canonical_and_source_bundle':True,'wiki_priority':'Current mapped per-field Wiki receipt before any estimate. metadata_only/superseded entries cannot claim confirmation. Accepted non-global project estimates retained; no model recalculation.','unknown_rows':blocked,'rows':proposals,'product_mutations':0,'cargo_runs':0,'network_reads':0}
(lane/'proposal.json').write_text(json.dumps(result,indent=2)+'\n');print({k:result[k]for k in ['row_count','counts','native_generation_matches_input','unknown_rows']})
