from pathlib import Path
import json,subprocess,hashlib
A=Path('/workspace/audit-continuation');D=A/'stack-forge-maxima-public-20261002';H='4f690c1e8a8966a4d074dde94d5a884dbb34fb94';R='/workspace/pr1437-timed-fields';inp={}
def read(p):
 b=subprocess.check_output(['git','show',H+':'+p],cwd=R);inp[p]=hashlib.sha256(b).hexdigest();return json.loads(b)
n=read('content/world/definitions/reference.json');items={r['identity']['key']:r for r in n['records'] if r.get('kind')=='Item'};stats=read('imports/tibiawiki/facts/items-stats.json')['records'];legacy=json.loads((A/'source-gaps-inventory.json').read_text());cohort=[]
for old in legacy['source_stack_yes']['records']:
 if old['native_stackable']!='UNKNOWN':continue
 key=old['item_key'];r=items[key];stack=r.get('semantics',{}).get('stack')
 if stack and stack['state']=='KNOWN':continue
 id=int(key.rsplit('i',1)[1]);src=stats.get(key) or stats.get(str(id));assert src and any(str(o.get('fields',{}).get('stackable','')).lower()=='yes' for o in src['observations'])
 cohort.append({'item_id':id,'target':r['identity'],'native_stack':stack,'native_record_state':'TYPED_SEMANTICS_STACK_UNKNOWN' if stack else 'IDENTITY_ONLY_NO_TYPED_SEMANTICS','retained_positive_source_page_coordinates':[{'page_id':o['page_id'],'revision_id':o['revision_id'],'revision_timestamp':o['revision_timestamp'],'url':o['url'],'content_sha256_declared':o['content_sha256']} for o in src['observations'] if str(o.get('fields',{}).get('stackable','')).lower()=='yes'],'qualified_maximum':None,'blocker':'INDEPENDENT_PER_ITEM_MAXIMUM_OR_FULLY_APPLICABLE_ACCEPTED_RULE_NOT_PROVEN_IN_BOUNDED_RESEARCH','additional_blocker':'NO_TYPED_NATIVE_SEMANTICS_AND_KNOWN_NAME' if stack is None else None})
assert len(cohort)==2493;assert sum(r['native_record_state']=='TYPED_SEMANTICS_STACK_UNKNOWN' for r in cohort)==2491
sourcepaths=[D/'manifest.json',D/'manifest-official-sections.json',D/'manifest-stack-rule-discovery.json',D/'official-controls.body',D/'official-characters.body',D/'official-interface.body',D/'official-trading.body',D/'stack-rule-category-and-search-browser-cdp-source.json',D/'stack-hints-updates-and-npc-browser-cdp-source.json',D/'google-maximum-stack-browser-cdp-toolresponse.json',D/'google-stackable100-browser-cdp-toolresponse.json',A/'stack2493-retained-ownraw-maximum-string-candidates-20261002.json',A/'stack-limit-tibiaqa-cases.json']
witnesses=[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in sourcepaths]
findings=[{'source':'Current official manual controls/interface/characters/trading','method':'NORMAL_PUBLIC_HTTPS_200','maximum_scope':'No applicable intrinsic stack maximum captured. Trading100 is transfer count,64000 MarketOffer quantity; neither maximum per single inventory stack.'},{'source':'Fandom Category:Stackable Items page74966 rev627492 2015-06-20','method':'REMOTE_DESKTOP_EXISTING_CHROME_CDP_PUBLIC_ANONYMOUS_API_200','quote':'These items can be stacked.','maximum_scope':'Positive boolean categorization only, no numeric maximum.'},{'source':'Fandom SupplyStash page86013 rev1057911 2024-04-15','method':'REMOTE_DESKTOP_EXISTING_CHROME_CDP_PUBLIC_ANONYMOUS_API_200','maximum_scope':'Single arbitrary-amount stash group and accounting increments100, distinct durable stash domain.'},{'source':'Fandom Hotkeys page6965 rev1180222 2026-04-29','method':'REMOTE_DESKTOP_EXISTING_CHROME_CDP_PUBLIC_ANONYMOUS_API_200','maximum_scope':'Slider step1000 and moving entire stacks are UI operations, not maximum.'},{'source':'Full retained own InfoboxObject frames for2493cohort','method':'LOCAL_RETAINED_CHROME_CDP_CAPTURE_JOIN','maximum_scope':'Zero maxlike owned parameters.41 scoped keyword hits concern effect stacking, appearance ranges, arbitrary examples, quest/world-transfer limits or grandfathered gold history. Ownbox corpus is not fullarticle absence proof.'},{'source':'Existing TibiaQA29207 /18254 fullbodies','method':'LOCAL_RETAINED_NORMAL_HTTP_CAPTURE; Google currentbrowser snippet discovery corroborates29207','maximum_scope':'Community general client limit hypothesis100 versus legacy gold exceptions. No exact current official version/applicability/variant proof. Repeating numerical consensus does not establish closed current2493 rule.'},{'source':'Pinned Crystalff7/Canary47 item.cpp fullsource','method':'NORMAL_PUBLIC_GITHUB_HTTPS_200','maximum_scope':'Forge globalconfig cap is an engine constraint, no perItem maximum. OTS remains hypothesis only.'}]
result={'schema':'STACK2493_WHOLE_COHORT_BOUNDED_MAXIMUM_RESEARCH/v1','published_native_head':H,'counts':{'diagnostic_cohort':2493,'actual_typed_native_stack_unknown':2491,'identity_only_records':2,'new_source_qualified_stack_maxima':0,'eligible_new_stack_promotions':0},'counts_are_not_global_incomplete_items':True,'identity_only_ids':[45322,45497],'record_join_inputs':inp,'source_findings':findings,'source_witnesses':witnesses,'records':sorted(cohort,key=lambda r:r['item_id']),'source_access':{'normal_fandom_api':'402 contactsiteowner','normal_br_api':'403 Cloudflare','normal_tibiopedia':'200 Setup gate, no item sourcefacts','normal_google':'200 redirect/interstitial; no normalreadableSERP','browser_fandom_br':'Actual Chrome154/CDP succeeded anonymouspublicAPI200; dedicated newresearchtabs only','browser_google':'Actual publicsearch readable; snippets are discovery only, not sourcebody proof','remote_project_or_system_mutations':'NONE'},'scope':'Bounded search/source join, not proof that no other source exists. No perItem default100, sourceabsence=false or native mutation.'}
p=A/'stack2493-whole-cohort-bounded-maximum-research-20261002.json';p.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(p,hashlib.sha256(p.read_bytes()).hexdigest(),result['counts'])
md='''# Stosy — aktualna kohorta i blokady źródłowe

Baza projektu: opublikowany `4f690c1e8a8966a4d074dde94d5a884dbb34fb94`.

Kohorta ma **2493 ID**: 2491 ma natywne pole stack w stanie UNKNOWN; 45322 i 45497 mają wyłącznie tożsamość, bez typed semantics i znanej nazwy. To nie jest liczba wszystkich nieukończonych Itemów.

W tym ograniczonym badaniu zakwalifikowano **0 nowych maksimów**. Zachowane pola własnych szablonów nie mają osobnej wartości maksimum. Oficjalny podręcznik odczytany normalnym HTTP opisuje przenoszenie stosów, handel i limity ofert; liczby 100 oraz 64000 w tych kontekstach nie są maksimum jednego stosu. Fandom odczytany przez Chrome/CDP opisuje kategorię stackable, stash, kroki suwaka i przykłady; nie zamyka reguły maksimum dla całej kohorty. Starsza odpowiedź społeczności TibiaQA nie jest dowodem zakresu aktualnej wersji i wyjątków. Historia stosów złota >100 wymaga osobnego rozstrzygnięcia wariantów/instancji.

Wszystkie 2493 ID, bieżące tożsamości, współrzędne dodatnich źródeł stackable i blokady zapisano w JSON obok. Źródła i metody dostępu mają skróty SHA256. Brak wartości w skanowanych źródłach nie dowodzi, że żadne inne źródło jej nie zawiera.

Fandom zwykłym HTTP zwrócił 402, BR 403, Tibiopedia stronę Setup; rzeczywisty Chrome przez Remote Desktop/CDP pozwolił odczytać publiczne API Fandom i BR. Na komputerze użytkownika wykonywano wyłącznie polecenia do sterowania przeglądarką i odczytu publicznych stron. Bez zmian projektu, systemu, instalacji, Cargo ani Git.
'''
p=A/'stack2493-whole-cohort-bounded-maximum-research-20261002.md';p.write_text(md);print(p,hashlib.sha256(p.read_bytes()).hexdigest())
