#!/usr/bin/env python3
"""Produce and check the Character progression ruleset files (ARCH-PROGRESSION-SOURCE-0).

  build_progression.py --check [--capture levels.csv]
  build_progression.py --write
  build_progression.py --init-evidence --capture levels.csv --source-url U --captured-on D --extraction-method M

--check needs no capture: the formula-generated bytes for 1..=K must hash to the committed
levels_sha256. With --capture the private capture is also checked byte for byte. The capture
itself is never written to the repository.
"""
import argparse
import hashlib
import sys
from pathlib import Path

import progression_lib as lib


def write_all(docs):
    for kind in ("table", "death", "reward", "differences"):
        lib.PATHS[kind].write_bytes(lib.pretty(docs[kind]))


def derived(evidence):
    return {
        "evidence": evidence,
        "table": lib.build_table(evidence),
        "death": lib.build_death(),
        "reward": lib.build_reward(),
        "differences": lib.build_differences(evidence["last_level"]),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--init-evidence", action="store_true")
    parser.add_argument("--capture", type=Path)
    parser.add_argument("--section-out", type=Path, help="write the canonical native gameplay progression section")
    parser.add_argument("--source-url")
    parser.add_argument("--captured-on")
    parser.add_argument("--extraction-method")
    args = parser.parse_args(argv)
    try:
        if args.init_evidence:
            if not (args.capture and args.source_url and args.captured_on and args.extraction_method):
                parser.error("--init-evidence needs --capture, --source-url, --captured-on, --extraction-method")
            data = args.capture.read_bytes()
            rows = data.count(b"\n")
            lib.check_capture(data, rows)
            if not 1 <= rows <= lib.TABLE_LEVELS:
                raise lib.ProgressionError("K outside 1..=2000")
            digest = hashlib.sha256(data).hexdigest()
            if digest != hashlib.sha256(lib.levels_csv(rows)).hexdigest():
                raise lib.ProgressionError("capture differs from the formula: stop with a BLOCKER")
            evidence = lib.build_evidence(rows, args.source_url, args.captured_on, args.extraction_method, digest)
            lib.PATHS["evidence"].parent.mkdir(parents=True, exist_ok=True)
            lib.PATHS["evidence"].write_bytes(lib.pretty(evidence))
            print(f"evidence written: K={rows}; set EXPERIENCE_EVIDENCE_LAST_LEVEL={rows}")
            return 0
        evidence = lib.strict_loads(lib.PATHS["evidence"].read_bytes())
        if args.write:
            write_all(derived(evidence))
        docs = lib.load_docs()
        lib.verify_documents(docs)
        if args.capture:
            lib.verify_capture_file(args.capture, evidence)
        if args.section_out:
            args.section_out.write_bytes(lib.canonical(lib.build_section(docs)))
        print("progression content ok:", lib.revisions(docs)["policy_revision"])
        return 0
    except lib.ProgressionError as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
