from pathlib import Path
import json,hashlib,subprocess,re
R=Path('/workspace/pr1437-resistances');S=Path('/workspace/audit-continuation');C=S/'document208-forge1-source-checkpoint-20261002';sha=lambda b:hashlib.sha256(b).hexdigest();base='2ec1f34f05fd89abbb041f313b0852c331ae2b53';assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()==base
files=['.github/workflows/item-authoring-schema.yml','apps/game-server/examples/materialize_content_world_project_v2.rs','apps/game-server/src/content/mod.rs','apps/game-server/src/content/item_forge3332_promotion.rs','docs/agents/evidence/OTV2-20261001-item-forge3332-source-qualification-v1.json','docs/agents/evidence/OTV2-20261002-item-forge3332-source-qualification-v2.json','docs/agents/evidence/OTV2-20261001-item-forge3332-promotion-v1.json','tools/content-schema/item-authoring/lower_item_forge3332_packet.py','tools/content-schema/item-authoring/test_lower_item_forge3332_packet.py']
assert not subprocess.check_output(['git','diff','--name-only','--','content','imports'],cwd=R,text=True).strip()
old='docs/agents/evidence/OTV2-20261001-item-forge3332-source-qualification-v1.json';assert (R/old).read_bytes()==(C/old).read_bytes()
for p in ['docs/agents/evidence/OTV2-20260925-item-enrichment-wave1-source-snapshot.json','docs/agents/evidence/OTV2-20260925-item-enrichment-wave1-staged.json','docs/agents/evidence/OTV2-20261001-item-document-promotion-v1.json','docs/agents/evidence/OTV2-20261002-item-elemental-magic-modifier-promotion-v1.json']:
 assert (R/p).read_bytes()==subprocess.check_output(['git','show',base+':'+p],cwd=R)
packet='docs/agents/evidence/OTV2-20261001-item-forge3332-promotion-v1.json';digest=sha((R/packet).read_bytes());assert digest in (R/'apps/game-server/src/content/item_forge3332_promotion.rs').read_text()
owners=json.loads((R/'content/world/definitions/declarations.json').read_text())['item_authoring'];assert sum('forge' in o for o in owners)==146
P=S/'forge3332-source-authoring-checkpoint-20261002';P.mkdir(exist_ok=True)
rows=[]
for p in files:
 target=P/p;target.parent.mkdir(parents=True,exist_ok=True);data=(R/p).read_bytes();target.write_bytes(data);rows.append({'path':p,'bytes':len(data),'sha256':sha(data)})
hand=sum(len((R/p).read_text().splitlines()) for p in files if p.endswith('.py') or p.endswith('item_forge3332_promotion.rs'))+10
m={'schema':'FORGE3332_SOURCE_ONLY_AUTHORING_CHECKPOINT/v1','phase':'SOURCE_STABLE_NO_CARGO_NO_FINAL_GENERATION_AWAIT_USE_PREDECESSOR','pr':1529,'branch':'codex/item-forge3332-sourcepair-20261002','worktree':str(R),'base':base,'source_files':rows,'new_source_atoms':2,'new_forge_profiles':1,'source_pair':{'classification':2,'max_tier':2},'existing_forge_profiles_preserved':146,'original_v1_proof_sha256':sha((R/old).read_bytes()),'current_v2_proof_sha256':sha((R/'docs/agents/evidence/OTV2-20261002-item-forge3332-source-qualification-v2.json').read_bytes()),'packet_sha256':digest,'parent_snapshot_manifest_sha256':sha((C/'manifest.json').read_bytes()),'all13_original_checkpoint_hashes_verified':True,'copy_scope':'ONLY5 Forge prototype files restored; no Document prototype copies;3 current additive glue files;1 new superseding source proof','source_role_limits':'BR article body unavailable; declared article digest remains capturecoordinate only. Actual immutable retained structuredpair artifact+canonical row independently hashed; explicit max_tier, no global table/default inference','binding_fix':'Both imported BR and Crystal forward/reverse bridges verified; only actual existing BR binding required in draft; Crystal proof is retained qualified_identity_bridge metadata, no fabricated draft binding','merge_contract':'source-only existingforge None-or-identical2/2; all sibling source metadata/native records/classes/admission untouched; duplicate/wrongfulltarget/conflict fail before write','handwritten_formatted_lines_including_glue':hand,'checks':{'Python':'PASS4','new_packet_check':'PASS','old10packet_checks':'PASS','Ruff':'PASS2','rustfmt_direct_no_compile':'PASS3scopedfiles','git_diff_check':'PASS','Native_content_and_imports':'NO_CHANGES','Rust_compile_LIB_Clippy':'NOT_RUN; explicitly no Cargo allocation','final_generation':'NOT_RUN; awaiting Root predecessorcarry'},'logs':[],'root_only_publisher':True,'no_commit_push_PR_or_remote_mutations':True}
for name in ['forge3332-source-tests.log','forge3332-packet-check.log','forge3332-old10-packet-checks.log','forge3332-ruff.log','forge3332-rustfmt-source-only.log']:
 p=S/name;m['logs'].append({'path':str(p),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size})
assert 'Ran 4 tests' in (S/'forge3332-source-tests.log').read_text();assert len((S/'forge3332-old10-packet-checks.log').read_text().splitlines())>=10
p=P/'manifest.json';p.write_text(json.dumps(m,sort_keys=True,indent=2)+'\n');(S/'forge3332-source-authoring-manifest.json').write_bytes(p.read_bytes());print('CHECKPOINT',P,'MANIFEST',sha(p.read_bytes()),'source9 handlines',hand,'packet',digest)
