//! Production-owned placeholder atlas (ADR-0020 section 4, child N2).
//!
//! The atlas is generated by the integer code below at run time. It embeds no binary file and no
//! third-party bytes, so there is no separate asset license: the output is a flat-colour test
//! pattern that follows the MPL-2.0 licence of this code. Legally approved art may replace it
//! later without changing the renderer. `oteryn-synthetic-assets` stays dev and test evidence.

/// Edge length of one atlas cell in pixels.
pub const CELL_PX: u32 = 16;
/// Number of cell columns in the atlas.
pub const COLUMNS: u32 = 4;
/// Number of cell rows in the atlas.
pub const ROWS: u32 = 2;

const BYTES_PER_PIXEL: usize = 4;

/// Named atlas cells. `index` is the row-major cell index used by the renderer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlaceholderCell {
    Grass,
    Dirt,
    Water,
    Stone,
    Player,
    Creature,
    OtherPlayer,
    Target,
}

impl PlaceholderCell {
    pub const ALL: [Self; 8] = [
        Self::Grass,
        Self::Dirt,
        Self::Water,
        Self::Stone,
        Self::Player,
        Self::Creature,
        Self::OtherPlayer,
        Self::Target,
    ];

    /// Row-major cell index inside the atlas.
    #[must_use]
    pub const fn index(self) -> u16 {
        match self {
            Self::Grass => 0,
            Self::Dirt => 1,
            Self::Water => 2,
            Self::Stone => 3,
            Self::Player => 4,
            Self::Creature => 5,
            Self::OtherPlayer => 6,
            Self::Target => 7,
        }
    }

    /// Terrain cells fill the whole cell; the others are shapes on a transparent background.
    #[must_use]
    pub const fn is_terrain(self) -> bool {
        matches!(self, Self::Grass | Self::Dirt | Self::Water | Self::Stone)
    }

    const fn colour(self) -> [u8; 3] {
        match self {
            Self::Grass => [64, 128, 56],
            Self::Dirt => [128, 96, 64],
            Self::Water => [48, 96, 176],
            Self::Stone => [120, 120, 128],
            Self::Player => [240, 208, 64],
            Self::Creature => [200, 56, 48],
            Self::OtherPlayer => [64, 200, 224],
            Self::Target => [255, 255, 255],
        }
    }
}

/// RGBA8 atlas of `columns * rows` square cells of `cell_px` pixels, row-major.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlaceholderAtlas {
    pub cell_px: u32,
    pub columns: u32,
    pub rows: u32,
    pub rgba: Vec<u8>,
}

impl PlaceholderAtlas {
    #[must_use]
    pub const fn width(&self) -> u32 {
        self.cell_px * self.columns
    }

    #[must_use]
    pub const fn height(&self) -> u32 {
        self.cell_px * self.rows
    }
}

/// Builds the deterministic placeholder atlas.
#[must_use]
pub fn placeholder_atlas() -> PlaceholderAtlas {
    let width = CELL_PX * COLUMNS;
    let height = CELL_PX * ROWS;
    let mut rgba = vec![0_u8; width as usize * height as usize * BYTES_PER_PIXEL];
    for cell in PlaceholderCell::ALL {
        let column = u32::from(cell.index()) % COLUMNS;
        let row = u32::from(cell.index()) / COLUMNS;
        for y in 0..CELL_PX {
            for x in 0..CELL_PX {
                let pixel = cell_pixel(cell, x, y);
                let offset = pixel_offset(width, column * CELL_PX + x, row * CELL_PX + y);
                rgba[offset..offset + BYTES_PER_PIXEL].copy_from_slice(&pixel);
            }
        }
    }
    PlaceholderAtlas {
        cell_px: CELL_PX,
        columns: COLUMNS,
        rows: ROWS,
        rgba,
    }
}

const fn pixel_offset(width: u32, x: u32, y: u32) -> usize {
    (y as usize * width as usize + x as usize) * BYTES_PER_PIXEL
}

fn shade(colour: [u8; 3], numerator: u16, denominator: u16) -> [u8; 3] {
    colour.map(|channel| u8::try_from(u16::from(channel) * numerator / denominator).unwrap_or(255))
}

fn cell_pixel(cell: PlaceholderCell, x: u32, y: u32) -> [u8; 4] {
    let colour = cell.colour();
    if cell.is_terrain() {
        // Darker one-pixel border so tile edges stay visible, plus a two-tone checker.
        let edge = x == 0 || y == 0 || x == CELL_PX - 1 || y == CELL_PX - 1;
        let tone = if edge {
            shade(colour, 3, 5)
        } else if (x / 4 + y / 4).is_multiple_of(2) {
            colour
        } else {
            shade(colour, 9, 10)
        };
        return [tone[0], tone[1], tone[2], 255];
    }
    // Shapes are measured in half pixels from the cell centre.
    let dx = (2 * i64::from(x) + 1) - i64::from(CELL_PX);
    let dy = (2 * i64::from(y) + 1) - i64::from(CELL_PX);
    let distance = dx * dx + dy * dy;
    let outer = 12 * 12;
    let inner = 9 * 9;
    let solid = cell != PlaceholderCell::Target;
    if distance > outer || (!solid && distance <= inner) {
        return [0, 0, 0, 0];
    }
    let tone = if solid && distance > inner {
        shade(colour, 2, 5)
    } else {
        colour
    };
    [tone[0], tone[1], tone[2], 255]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pixel(atlas: &PlaceholderAtlas, cell: PlaceholderCell, x: u32, y: u32) -> [u8; 4] {
        let column = u32::from(cell.index()) % atlas.columns;
        let row = u32::from(cell.index()) / atlas.columns;
        let offset = pixel_offset(
            atlas.width(),
            column * atlas.cell_px + x,
            row * atlas.cell_px + y,
        );
        [
            atlas.rgba[offset],
            atlas.rgba[offset + 1],
            atlas.rgba[offset + 2],
            atlas.rgba[offset + 3],
        ]
    }

    #[test]
    fn atlas_dimensions_match_the_pixel_buffer() {
        let atlas = placeholder_atlas();
        assert_eq!((atlas.width(), atlas.height()), (64, 32));
        assert_eq!(atlas.rgba.len(), 64 * 32 * 4);
        assert_eq!(
            PlaceholderCell::ALL.len(),
            (atlas.columns * atlas.rows) as usize
        );
    }

    #[test]
    fn cell_indices_are_dense_and_row_major() {
        for (expected, cell) in PlaceholderCell::ALL.iter().enumerate() {
            assert_eq!(usize::from(cell.index()), expected);
        }
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(placeholder_atlas(), placeholder_atlas());
    }

    #[test]
    fn terrain_cells_are_fully_opaque_and_distinct() {
        let atlas = placeholder_atlas();
        let mut centres = Vec::new();
        for cell in PlaceholderCell::ALL
            .into_iter()
            .filter(|cell| cell.is_terrain())
        {
            for y in 0..CELL_PX {
                for x in 0..CELL_PX {
                    assert_eq!(pixel(&atlas, cell, x, y)[3], 255);
                }
            }
            centres.push(pixel(&atlas, cell, 5, 5));
        }
        centres.sort_unstable();
        centres.dedup();
        assert_eq!(centres.len(), 4);
    }

    #[test]
    fn sprite_cells_are_transparent_at_the_corners_and_opaque_at_the_centre() {
        let atlas = placeholder_atlas();
        for cell in [
            PlaceholderCell::Player,
            PlaceholderCell::Creature,
            PlaceholderCell::OtherPlayer,
            PlaceholderCell::Target,
        ] {
            assert_eq!(pixel(&atlas, cell, 0, 0)[3], 0, "{cell:?} corner");
            assert_eq!(pixel(&atlas, cell, 15, 15)[3], 0, "{cell:?} corner");
        }
        for cell in [
            PlaceholderCell::Player,
            PlaceholderCell::Creature,
            PlaceholderCell::OtherPlayer,
        ] {
            assert_eq!(pixel(&atlas, cell, 8, 8)[3], 255, "{cell:?} centre");
        }
        // The target marker is a ring: hollow centre, opaque on the ring.
        assert_eq!(pixel(&atlas, PlaceholderCell::Target, 8, 8)[3], 0);
        assert_eq!(pixel(&atlas, PlaceholderCell::Target, 8, 2)[3], 255);
    }
}
