"""Read-only accepted schema/validator audit; no Item claims or project mutations."""
from pathlib import Path
import hashlib,json,subprocess,collections
A=Path('/workspace/audit-continuation');R=Path('/workspace/pr1437-stack-publish')
H='4f690c1e8a8966a4d074dde94d5a884dbb34fb94';T='88edf552b323cef8cb68cef5b10949fbf0c85424';w=[]
def digest(b):return hashlib.sha256(b).hexdigest()
def raw(p,h=H):
 b=subprocess.check_output(['git','show',h+':'+p],cwd=R);w.append({'commit':h,'path':p,'sha256':digest(b),'bytes':len(b)});return b
P='tools/content-schema/item-authoring/'
def doc(p,h=H):return json.loads(raw(P+p,h))
native_schema=doc('item.schema.json');tax_schema=doc('item.schema.json',T);catalog=doc('profile-catalog.json');assert catalog==doc('profile-catalog.json',T)
validator=raw(P+'validate_item.py').decode();tax_validator=raw(P+'validate_item.py',T).decode();deps=doc('item-dependencies.schema.json');manifest=doc('item-import-readiness.schema.json');evidence=doc('real-source-evidence.schema.json')
assert 'tuple(row["common_capabilities"])' in validator and 'normally expects capability' in validator and 'return errors, warnings' in validator
assert 'dispositions must equal the complete source field inventory' in validator
assert 'no runtime qualification' in validator
caps=['physical','stack','requirements','equipment','weapon','protection','modifiers','charges','temporal','container','imbuement','forge','proficiency','consumable','fluid','readable','light','use','lifecycle','availability','trade','presentation']
def constraints(node,path,rows):
 if not isinstance(node,dict):return
 obligation={k:node[k] for k in ['required','dependentRequired','oneOf','anyOf','allOf','if','then','else','minItems'] if k in node}
 if obligation:rows.append({'schema_pointer':path,'constraints':obligation})
 for k,v in node.get('properties',{}).items():constraints(v,path+'/properties/'+k,rows)
 if isinstance(node.get('items'),dict):constraints(node['items'],path+'/items',rows)
required={}
for cap in caps:
 rows=[];name=native_schema['properties'][cap]['$ref'].split('/')[-1];constraints(native_schema['$defs'][name],'#/$defs/'+name,rows);required[cap]={'applies_when':'ONLY when capability is authored or a qualified source fact maps here; family common list alone is not a requirement','constraints':rows}
# Every nested group has its own conditional schema; include all required-bearing defs, not guessed fields.
nested=[]
for name,node in native_schema['$defs'].items():constraints(node,'#/$defs/'+name,nested)
templates={};template_details={}
for h in [H,T]:
 paths=subprocess.check_output(['git','ls-tree','-r','--name-only',h,P+'templates'],cwd=R,text=True).splitlines();rows=[]
 for p in paths:
  if not p.endswith('.json'):continue
  x=json.loads(raw(p,h));assert x['delivery_task_eligible'] is False
  rows.append({'path':p,'family_profile':x['family_profile'],'identity':x['identity'],'declared_capabilities':[c for c in caps if c in x],'delivery_task_eligible':False,'evidence_status':'SYNTHETIC_TEMPLATE_VALUES_NOT_SOURCE_FACTS'})
 templates[h]=rows;template_details[h]={'templates':len(rows),'covered_profiles':len({r['family_profile'] for r in rows}),'uncovered_profiles':sorted(set(p['profile_id'] for p in catalog['profiles'])-{r['family_profile'] for r in rows})}
family_classes={r['if']['properties']['family_profile']['const']:r['then']['properties']['taxonomy']['properties']['item_class']['enum'] for r in tax_schema['allOf']}
profiles=[]
for p in catalog['profiles']:
 f=p['profile_id'];profiles.append({**p,'mandatory_capabilities_from_family_alone':[],'common_capability_enforcement':'WARNING_ONLY in validate(); expected_capabilities is catalog metadata, not root required','taxonomy_overlay_allowed_item_classes':family_classes[f],'native4f_family_itemclass_constraint_present':False,'native4f_templates':[r['path'] for r in templates[H] if r['family_profile']==f],'taxonomy88ed_templates':[r['path'] for r in templates[T] if r['family_profile']==f],'applicability_gate':'Use exact accepted source facts/catalog routes plus authored groups and declared relationships; do not copy template defaults or make every optional native leaf KNOWN'})
assert len(profiles)==22 and len(templates[T])==23 and not template_details[T]['uncovered_profiles']
rule=lambda i,status,scope,check:{'id':i,'authority':status,'scope':scope,'check':check}
gates=[
 rule('G1_IDENTITY_AND_DOMAIN','EXISTING_SOURCE_QUALIFICATION_PLUS_SCHEMA','every Item','Unique exact current numeric binding and target identity; preserve own-ID-first and all-present source agreement; separate portable Item versus Terrain/WorldObject/instance state. Qualified family/navigation metadata alone is not native admission.'),
 rule('G2_FAMILY_AND_ENVELOPE','EXISTING_SCHEMA','every authoring Item','identity, display_name, family_profile, delivery_task_eligible, taxonomy present; taxonomy item_class and primary present. Validate family/item_class using taxonomy88ed constraint only after real composition; native4f schema alone does not impose it.'),
 rule('G3_FIELD_INVENTORY','EXISTING_VALIDATE_WITH_MANIFEST; REQUIRED_FOR_PROPOSED_IMPORT_COMPLETION_GATE','every in-scope retained source frame','Pinned source identities and real capture timestamps; every source field occurrence has exactly one disposition, and dispositions equal complete field_inventory. No unsupported_source_field, unresolved_semantics or conflict may pass import-readiness. Missing source field remains UNKNOWN; absence is not FALSE/N/A.'),
 rule('G4_INTRINSIC_TYPED_PROJECTION','EXISTING_CATALOG_ROUTES_AND_PACKET_GUARDS','every mapped intrinsic source fact','Destination exists with admitted unit/type/exact value and accepted owner (native semantics or ItemAuthoring), all applicable guards and known/conflict-state preservation. Rational percentage points, relative p/100, milliseconds and source units stay distinct. OTS hypotheses remain labeled hypotheses; engine agreement does not become official truth.'),
 rule('G5_CONDITIONAL_CAPABILITY_VALIDITY','EXISTING_SCHEMA_AND_VALIDATE','only authored/applicable capability','Apply exact nested required/oneOf/anyOf constraints and semantic coherence; missing common capabilities produce warning, not failure. Equipment slot/hands/reservation, damage minimum<=maximum, resource/vector uniqueness, imbuement exclusion, lifecycle decay consistency. No generic all-optional-known rule.'),
 rule('G6_EXTERNAL_RELATION_CLOSURE','EXISTING_VALIDATE_AND_SOURCE_DISPOSITIONS','every declared or mapped dependency','Resolve every exact used definition/asset/proficiency crosswalk to its owning domain; no duplicate or unused declarations. Quest/drop/trade/actor/effect/formula/FX/audio relations retain source owning disposition; identity of a sound/effect alone does not establish its activation/consumer binding.'),
 rule('G7_PRESENTATION_AND_RESOURCE_STATUS','EXISTING_VALIDATE; FULL_RENDERABILITY_SEPARATE','when presentation/assets declared or source routes demand them','appearance_binding requires actual pinned presentation payload and valid frame geometry/sprite counts. Sprite-atlas absence is a warning in structural validator, a real-example blocker, and must remain explicit in any renderability claim. Do not infer zero/missing FX from no source binding.'),
 rule('G8_EVERY_AUTHORED_LEAF_EVIDENCE','EXISTING_REAL_EXAMPLE_RULE; PROPOSED_GENERALIZATION_OUTSIDE_6_FIXTURES','every authored source-claiming Item','field_evidence and non_source_defaults exactly partition authored leaves (validator-specific exceptions preserved). Defaults/normalizations are labeled, not source-proven. Existing validate_real_example is a closed real-example contract, not evidence that all34031 rows were checked.'),
 rule('G9_PUBLISHED_COMPOSITION','EXISTING_PACKET_GUARDS; PROPOSED_GLOBAL_AGGREGATE_GATE','after accepted source patch','Exact final published parent/source/packet SHA, actual typed owner equality, deterministic native/tree/migration comparison, preservation of unrelated fields, approved dependencies. Overlay taxonomy/world/native reports are not proof that their branches were integrated.'),
 rule('G10_RUNTIME_READINESS','NOT_ESTABLISHED_AS_GLOBAL_PER_ITEM_CONTRACT','separate runtime/playable claim','Existing Item authoring CLI always reports runtime_qualified=false. Rune ability/formula, modifier target/evaluation/priority, interaction/effects, sprites/resources and actor rules need their actual accepted owning contracts; do not substitute source metadata completion for runtime readiness.')]
record_shape={'target':'exact family/key/revision','scope':'explicit source versions/cutoff/published head','family_profile':'admitted family or held reason','source_fields':[{'locator':'actual retained source coordinates','field':'literal source field','disposition':'mapped / accepted external or omission / conflict or unresolved','typed_owner':'actual native path / authoring / external owning relation','state':'KNOWN or actual state','proof_sha256':'real proof or null','blocker':'exact missing mapping/unit/identity/source/owner reason or null'}],'capabilities':[{'name':'authored or independently source-applicable group','applicability':'PROVEN_APPLICABLE / PROVEN_NOT_APPLICABLE / UNKNOWN_NO_SOURCE','required_by':'actual schema conditional or actual source route; never common list alone','missing_applicable_fields':[],'coherence_errors':[]}],'relations':[{'owning_domain':'actual accepted owner','source_evidence':'real record or null','binding_status':'resolved / held / unsupported / no observed fact'}],'gate_results':{g['id']:'PASS / HOLD / NOT_APPLICABLE_WITH_PROOF / NOT_EVALUATED' for g in gates},'source_import_complete':'null until G1-G9 evaluated for declared scope and proposed aggregate gate accepted','runtime_qualified':'null until actual owning runtime contract checked'}
report={'schema':'OTERYN_ITEM_COMPLETION_CONTRACT_READONLY_CHECKLIST/v1','native_baseline':H,'taxonomy_overlay_baseline':T,'scope':'Audit of accepted authoring structures and finite proposed per-Item completion gate; no repo integration, validator run over Item pool, runtime qualification or complete Item count','profile_count':22,'templates_by_head':template_details,'composition_requirement':'Carry family22 itemclass +template23 +imbuement max tiers from taxonomy while preserving native partial-leech fix. No current integrated candidate tested here.','root_required_authoring_fields':native_schema['required'],'taxonomy_required_fields':native_schema['$defs']['taxonomy']['required'],'mandatory_capabilities_from_family_alone':[],'profile_rows':profiles,'conditional_capability_contracts':required,'all_nested_schema_obligations':nested,'dependencies_root_required':deps['required'],'manifest_root_required':manifest['required'],'existing_authoring_validator_boundary':'portable Item authoring structure and declared dependency closure; no runtime qualification','real_example_closed_scope':{'minimum_source_claim_gate':'Exact field_evidence/non_source_defaults authored leaf partition','fixed_blockers':['sprite_atlas_not_admitted','runtime_lowering_not_implemented'],'conditional_blockers':['rune ability_binding_not_admitted and combat_formula_not_admitted','fluid fluid_interaction_binding_not_admitted','source sounds yum_sound_asset_not_admitted','missing canonical numeric identity','unadmitted proficiency crosswalk when applicable'],'warning':'These checks apply to retained real-example fixture contract, not automatic current full-pool readiness counts'},'checklist':gates,'proposed_per_item_record_shape':record_shape,'definition_of_done':{'categorized':'Exact accepted family metadata and domain disposition established; not native playable admission','source_coverage_complete':'Every retained field in explicitly pinned source scope has one supported disposition; external relation omission is explicit, not lost','typed_import_complete':'Every accepted applicable intrinsic source mapping exists at actual stored typed owner with exact value; all conditional authoring and declared dependency constraints pass; no unresolved applicable source fact within declared scope','runtime_qualified':'Separate owning runtime contract; NOT_ESTABLISHED globally by current Item authoring validator','all_zero_claim':'Only after every scoped Item has evaluated gate records with no open applicable source/import/relationship blocker; cannot infer from zero missing templates or successful batch counts'},'fully_verified_status':'NOT_ESTABLISHED','fully_verified_count':None,'incomplete_count':None,'input_witnesses':w,'validation_performed':'Read-only byte/digest/code/schema/catalog consistency audit; no Cargo, whole-pool validator or project mutation'}
q=A/'item-completion-contract-checklist-after-forge4f-20261002.json';q.write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n')
md=['Kontrakt ukończenia Item: audyt po Forge4f','',f'Źródła: native `{H}`, overlay taxonomy `{T}`. To dwa osobne opublikowane drzewa, nie sprawdzony wspólny kandydat.','', 'Istniejący walidator określa poprawność struktury authoring i zadeklarowanych zależności. Nie określa globalnej gotowości rozgrywki: wynik CLI ma runtime_qualified=false. Nie istnieje uniwersalna lista wszystkich wymaganych Known dla każdej rodziny. Pełny licznik ukończonych Item pozostaje NULL / NOT_ESTABLISHED.','', 'Pięć wymaganych pól głównych: identity, display_name, family_profile, delivery_task_eligible, taxonomy. Taxonomy wymaga item_class i primary. Pozostałe capability groups są warunkowe. common_capabilities z katalogu wywołuje ostrzeżenia; expected_capabilities nie jest listą wymaganych pól.','', '22 profile i 23 szablony / zero brakujących profili dotyczą taxonomy88ed. Native4f ma ten sam katalog22, ale13 szablonów /10 niepokrytych profili. Wszystkie23 są przykładami z delivery_task_eligible=false; rune charges=1/stack=100 i inne literalne wartości szablonów nie są dowodami źródłowymi. Przed wspólną walidacją trzeba zachować jednocześnie nowe family/itemclass+imbuement maxima z taxonomy oraz poprawkę partial leech z native.','', '| Rodzina | Common: tylko ostrzeżenia | Optional: tylko po potwierdzeniu applicability | Item class w taxonomy88ed | Szablony overlay/native4f |','|---|---|---|---|---|']
for p in profiles:md.append('| '+p['profile_id']+' | '+', '.join(p['common_capabilities'])+' | '+(', '.join(p['optional_capabilities']) or '—')+' | '+', '.join(p['taxonomy_overlay_allowed_item_classes'])+' | '+str(len(p['taxonomy88ed_templates']))+'/'+str(len(p['native4f_templates']))+' |')
md+=['','Warunkowe wymagania mają dokładne granice: authored equipment wybiera compact slot+hands lub niepuste patterns z pattern_id+slot+hands; charges wymaga dodatniego count; forge wymaga classification+max_tier; imbuement wymaga slot_count, nie domyślnego pełnego zestawu rodzin. Partial leech wymaga resource oraz co najmniej chance albo amount, bez wypełniania nieobecnej wartości zerem. Pełna lista zagnieżdżonych constraints i źródłowe SHA są w JSON.','','Proponowana skończona karta kontroli dla każdego Item:']
for g in gates:md.append('\n'+g['id']+' — '+g['check']+' Autor: '+g['authority']+'.')
md+=['','Cztery osobne wyniki: categorized; complete source field coverage dla zadeklarowanych źródeł; complete typed import z zamkniętymi zadeklarowanymi zależnościami; osobno runtime-qualified. UNKNOWN bez odpowiedniego źródła nie jest automatycznym błędem. Jawny source-fact bez typed projection jest konkretnym import gap. Relacja do Quest/Ability/Effect/FX/audio należy do właściwego właściciela i wymaga dowodu/bindingu, jeżeli źródło ją deklaruje.','','Manifest source inventory jest opcjonalnym argumentem istniejącego CLI; wymaganie go dla pełnego globalnego ukończenia jest wyraźnie oznaczoną propozycją agregacji, nie dotychczasową obowiązkową walidacją całej puli. Podobnie zamknięte real-example leaf proofs nie zostały wykonane dla34031 Item. Brak autorytatywnego globalnego kontraktu runtime nie blokuje dalszego źródłowego uzupełniania; blokuje jedynie twierdzenie „wszystkie gotowe/zero”.']
m=A/'item-completion-contract-checklist-after-forge4f-20261002.md';m.write_text('\n'.join(md)+'\n');print(json.dumps({'json':str(q),'json_sha256':digest(q.read_bytes()),'md':str(m),'md_sha256':digest(m.read_bytes()),'profiles':22,'template_counts':template_details,'fully_verified_count':None},indent=2))
