"""External immutable-source composition plan. Does not apply project mutations."""
from pathlib import Path
import subprocess,json,hashlib,ast
R=Path('/workspace/pr1437-stack-publish');A=Path('/workspace/audit-continuation');H='4f690c1e8a8966a4d074dde94d5a884dbb34fb94';T='88edf552b323cef8cb68cef5b10949fbf0c85424';P='tools/content-schema/item-authoring/';w=[]
sha=lambda b:hashlib.sha256(b).hexdigest()
def raw(p,h=H):
 b=subprocess.check_output(['git','show',h+':'+p],cwd=R);w.append({'path':p,'commit':h,'sha256':sha(b),'bytes':len(b)});return b
def j(p,h=H):return json.loads(raw(p,h))
def pure_constant(source,name):
 t=ast.parse(source);return ast.literal_eval(next(n.value for n in t.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id==name))
engine=raw(P+'engine_items.py');catalog=raw(P+'source_field_catalogs.py');assert sha(engine)=='28644c0fcc88f364992670489f7d458f827a9cd1db023b7f5ce0a9ae32d08c1a';assert sha(catalog)=='8250880aaa89b7c5fa1593d5738a478b0d09e1ef9ef9cef630cb5da172d634bc';assert pure_constant(engine.decode(),'PROFILE_ITEM_CLASS')==pure_constant(raw(P+'engine_items.py',T).decode(),'PROFILE_ITEM_CLASS')
copy=[]
for path in subprocess.check_output(['git','ls-tree','-r','--name-only',T,P+'templates'],cwd=R,text=True).splitlines():
 if not path.endswith('.json'):continue
 exists=subprocess.run(['git','cat-file','-e',H+':'+path],cwd=R,capture_output=True).returncode==0
 if exists:continue
 b=raw(path,T);copy.append({'path':path,'source_commit':T,'sha256':sha(b),'introduced_commit':'7aa9351d26f76734412a1492b28d6a519fdef70f','introduced_pr':1437,'action':'Copy exact already-published template bytes to newly allocated native integration successor; synthetic not source facts'})
assert len(copy)==10
schema=j(P+'item.schema.json');tax=j(P+'item.schema.json',T);assert len(tax['allOf'])==22 and 'allOf' not in schema
builder=raw(P+'build_formal_schema.py');verify=raw(P+'verify_formal_schema.py');assert b'partial leech' in verify
changes=[{'path':P+'build_formal_schema.py','action':'Add exact published family/itemclass allOf constructor (340a6) and missing_profiles template block (7aa9351) to actual native generator. Leave native leech anyOf intact; no engine import/function patch required because current PROFILE_ITEM_CLASS is identical.'},{'path':P+'item.schema.json','action':'Regenerate from composed generator; expected sole schema delta is22 root family-profile conditional allOf rules. Do not replace whole taxonomy schema (would regress partial leech). If approved optional imbuement maximum schema added later, count it independently.'},{'path':P+'verify_formal_schema.py','action':'Replace exact13 template count with catalog-profile set equality; add family/taxonomy mismatch regression; set family_profile=container in existing engine-type container destination case so expected-valid fixture satisfies new constraint. Preserve native partial-leech cases and every later source check.'},{'path':P+'formal-schema-validation-report.json','action':'Regenerate full formal report from actual composed source; do not import older report which omits native partial-leech regressions.'},{'path':P+'README.md','action':'State actual composed22profiles23templates and preserve current native source/runtime boundaries.'},{'path':'.github/workflows/item-authoring-schema.yml','action':'Add specific new template/checker routes only if absent; preserve all native/context/current predecessor packet checks. Source-only Python checks suffice for schema/template composition; Cargo only if actual Rust changes.'}]
paths=subprocess.check_output(['git','ls-tree','-r','--name-only',H,'docs/agents/evidence'],cwd=R,text=True).splitlines();packets=[]
for path in paths:
 if not (path.endswith('.json') and 'promotion' in path and ('20261001-item-' in path or '20261002-item-' in path)):continue
 b=raw(path);packet=json.loads(b);hits=[]
 pinned_source_digests={sha(engine),sha(catalog)}
 def walk(v,ptr=''):
  if isinstance(v,dict):
   if v.get('path') in [P+'engine_items.py',P+'source_field_catalogs.py',P+'item.schema.json',P+'build_formal_schema.py',P+'verify_formal_schema.py']:hits.append({'pointer':ptr,'pin':v})
   for k,t in v.items():
    if k in [P+'engine_items.py',P+'source_field_catalogs.py',P+'item.schema.json',P+'build_formal_schema.py',P+'verify_formal_schema.py'] or isinstance(t,str) and t in pinned_source_digests:hits.append({'pointer':ptr+'/'+k,'pin':t})
    walk(t,ptr+'/'+k)
  elif isinstance(v,list):
   for i,t in enumerate(v):walk(t,ptr+'/'+str(i))
 walk(packet);packets.append({'path':path,'sha256':sha(b),'direct_pinned_dependency_hits':hits,'schema_or_generator_path_pin':any(x['pin'].get('path') in [P+'item.schema.json',P+'build_formal_schema.py',P+'verify_formal_schema.py'] if isinstance(x['pin'],dict) else False for x in hits)})
# Primary packet schema/filename differs; inspect it independently rather than omit.
stats_path='docs/agents/evidence/OTV2-20260930-item-stats-promotion-v2.json'
found=subprocess.run(['git','cat-file','-e',H+':'+stats_path],cwd=R,capture_output=True).returncode==0
if found:
 b=raw(stats_path);packets.append({'path':stats_path,'sha256':sha(b),'schema_or_generator_path_pin':False,'inspection':'Read current lower_wiki_stats_packet.py source: packet compiler metadata binds compiler, raw snapshots/qualified source holds and bindings, not Item authoring schema/generator'})
# Exact authoring original published diffs and final source versions are retained in the plan as evidence.
origin_commits=[]
for c in ['340a6be43b1beead30c145a4223a146a1024cca9','7aa9351d26f76734412a1492b28d6a519fdef70f']:
 paths=subprocess.check_output(['git','diff-tree','--no-commit-id','--name-only','-r',c],cwd=R,text=True).splitlines();origin_commits.append({'commit':c,'pr':1437,'owned_paths':paths,'full_batch_warning':'Includes taxonomy/converter/sourcecatalog changes; NOT a drop-in whole-tree replacement of current Native head'})
future=[]
for path in ['content/items/taxonomy/items.json','content/items/relations/items.json']:
 base=j(path);overlay=j(path,T);future.append({'path':path,'current_native4f_rows':len(base['records']),'published_taxonomy88ed_rows':len(overlay['records']),'status':'MISSING_FROM_COMPOSED_NATIVE_HEAD_NOT_NOT_CREATED','integration_requirement':'Whole published taxonomy batch qualification + actual current identity/name/domain/relation-owner coherence and deterministic tree/census receipt; never replace current source/native owners by old overlay without closed comparison'})
report={'schema':'OTERYN_ITEM_FAMILY_CONTRACT_COMPOSITION_PLAN/v1','status':'READONLY_SOURCE_PLAN_NOT_APPLIED','native_baseline':H,'published_taxonomy_head':T,'published_taxonomy_pr':1523,'original_contract_pr':1437,'original_contract_commits':origin_commits,'source_pins_to_preserve':{P+'engine_items.py':sha(engine),P+'source_field_catalogs.py':sha(catalog)},'profile_class_map_same':True,'scope_minimal_contract_batch':'10 already-published templates +22 family/itemclass constraints + executable full-profile coverage; no native facts/engine decoder/sourcecatalog change','exact_template_copies':copy,'composed_path_changes':changes,'schema_component_to_merge':{'allOf':tax['allOf'],'native_partial_leech_to_preserve':schema['$defs']['leechModifier']},'packet_dependency_inventory':packets,'packet_seal_effect':'No listed promotion packet pins schema/generator/verify paths. If decoder/catalog/compiler/raw source proofs are preserved, their packet SHAs/Rust constants and generated native facts must stay byte-identical. Re-run original packet checks/current-historical context after actual composition; later Weapon/Default packets must be checked from their actual published successor, not assumed here.','optional_imbuement_scope':'Taxonomy also has allowed_family_max_tiers and validator uniqueness/exclusion checks; full parser/catalog implementation changes sourcecatalog825/engine28644 pins, so keep this independent unless Root deliberately allocates a separate source-preserving wrapper/contract extension. Do not silently replace engine/catalog to recover taxonomy version.','full_published_data_composition_pending':future,'full_composition_warning':'Minimal schema/template batch does not integrate12252 family rows or world3ed49 catalogs. Current native taxonomy164 remains actual. Complete native/taxonomy/world composition requires separate fully qualified published-chain receipt and sourceguard comparison, no perpetual overlay claim.','required_checks':['Exact published source blobs and template checksums','Generator --check / schema equivalence / formal verifier with all current cases and partial leech preserved','22profile coverage and23template count on actual composed successor','Reject wrong family/item_class; preserve accepted weapon_distance/food/fluid class alternatives','Every old packet/compiler/decoder/catalog digest unchanged; run existing packet --check and current/historical context compatibility','No changes to actual native69 shards/reference34031Item/all57320, owner316, source203/relations278 unless allocated full-data composition reports exact justified delta','Ruff/schema style/diff/checks and independent bounded source review; no Cargo for Python/schema-only batch'],'input_witnesses':w}
p=A/'item-family-contract-composition-plan-after-forge4f-20261002.json';p.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');q=A/'item-family-contract-composition-plan-after-forge4f-20261002.md';q.write_text('Plan integracji istniejącego kontraktu rodzin do faktycznego native successor\n\nTaxonomy88ed/PR1523 zawiera22profiles23templates; oryginalne template/family constraints opublikowano w PR1437:340a6 oraz7aa9351. Native4f nadal ma13templates/12coveredprofiles oraz taxonomy164rows;10templates nie są „nieutworzone”, lecz nie są w złożonym native head.\n\nMinimalny wykonany w nowym draft carry:10 exact template blobs + addytywny family allOf w obecnym build_formal_schema/item.schema + właściwy formal verifier/report. PROFILE_ITEM_CLASS jest już identyczny; engine28644 i sourcecatalog825 muszą pozostać byte-identical. Zachować partial leech anyOf i native tests. Opublikowany taxonomy schema wymaga obu leech pól, więc skopiowanie go w całości byłoby regresją.\n\nMerge verifier: profile-set coverage zamiast „13”; family/itemclass mismatch fixture; istniejący engine-type container fixture musi zmieniać również family_profile=container. Wszystkie późniejsze checks i context workflow zachować. Nie importować starego generated report. JSON wymienia exact source SHA/path/commit dla10templates, pełne oryginalne owned paths i fragment allOf.\n\nPrzejrzane current promotion packets nie pinują Item schema/generator/formal verifier. Przy pozostawieniu decoder/catalog/compiler/source witnesses nie trzeba ich resealować ani zmieniać Rust packet pins. Trzeba wykonać wszystkie packet checks na realnym nowym successor; przyszłe Weapon/Default sprawdzić po faktycznej publikacji.\n\nPełna integracja rodzin/world to dodatkowa konkretna praca: native taxonomy164 vs published12252 oraz relations203 vs729. Nie wolno wstawić starego overlay na aktualne owner316/source203/relations278, Known nazwy i69 native shards bez closed sourceguard/current target/owner comparison oraz qualified composition receipt. Minimalne template/schema carry samo nie zamyka tej pracy.\n');print(json.dumps({'json':str(p),'sha256':sha(p.read_bytes()),'md':str(q),'md_sha256':sha(q.read_bytes()),'copy_templates':len(copy),'packets':len(packets)},indent=2))
